import * as I from 'lucide-react'

// name → lucide component map. Unknown names fall back to Circle.
const MAP = {
  LayoutDashboard: I.LayoutDashboard,
  Globe: I.Globe,
  Map: I.Map,
  BrainCircuit: I.BrainCircuit,
  Sparkles: I.Sparkles,
  AlertTriangle: I.AlertTriangle,
  Users: I.Users,
  MessageSquare: I.MessageSquare,
  Cpu: I.Cpu,
  Antenna: I.Antenna,
  Bell: I.Bell,
  Building2: I.Building2,
  BarChart3: I.BarChart3,
  Satellite: I.Satellite,
  Settings: I.Settings,
  Search: I.Search,
  ZoomIn: I.ZoomIn,
  ZoomOut: I.ZoomOut,
  Home: I.Home,
  Loader2: I.Loader2,
  X: I.X,
  ChevronRight: I.ChevronRight,
  ArrowUpRight: I.ArrowUpRight,
  ArrowDownRight: I.ArrowDownRight,
  TrendingUp: I.TrendingUp,
  TrendingDown: I.TrendingDown,
  CheckCircle2: I.CheckCircle2,
  Clock: I.Clock,
  MapPin: I.MapPin,
  Radio: I.Radio,
  Battery: I.Battery,
  Wifi: I.Wifi,
  Truck: I.Truck,
  ShieldAlert: I.ShieldAlert,
  Crosshair: I.Crosshair,
  Layers: I.Layers,
  RefreshCw: I.RefreshCw,
  Send: I.Send,
  Plus: I.Plus,
  Filter: I.Filter,
  Download: I.Download,
  PlayCircle: I.PlayCircle,
  Waves: I.Waves,
  Tornado: I.Tornado,
  ThermometerSun: I.ThermometerSun,
  Thermometer: I.Thermometer,
  Snowflake: I.Snowflake,
  Activity: I.Activity,
  Mountain: I.Mountain,
  Flame: I.Flame,
  CloudFog: I.CloudFog,
  CloudRain: I.CloudRain,
  Droplets: I.Droplets,
  SunDim: I.SunDim,
  Sun: I.Sun,
  Radar: I.Radar,
  Cross: I.Cross,
  GraduationCap: I.GraduationCap,
  Zap: I.Zap,
  TrainFront: I.TrainFront,
  Route: I.Route,
  Plane: I.Plane,
  Router: I.Router,
  Wind: I.Wind,
  CloudLightning: I.CloudLightning,
  Eye: I.Eye,
  Siren: I.Siren,
  CircleAlert: I.CircleAlert,
  TriangleAlert: I.TriangleAlert,
  Atom: I.Atom,
  User: I.User,
  BarChart2: I.BarChart2,
  Gauge: I.Gauge,
  Image: I.Image,
  List: I.List,
  Circle: I.Circle,
}

export function Icon({ name, size = 16, className = '', ...rest }) {
  const C = MAP[name] || I.Circle
  return <C size={size} className={className} strokeWidth={1.75} {...rest} />
}